import Head from "next/head";
import About from "../components/About";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import Contact from "../components/Contact";
import Services from "../components/Services";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chicode || Web Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://res.cloudinary.com/da7gjdcwj/image/upload/v1653990805/chicode/images/favicon-32x32_op3oif.png" />
      </Head>

      <Hero />
      <About />
      <Skills />
      <Services />
      {/*<Projects />*/}
      <Contact />
    </div>
  );
}
